### ISSUE TITLE
Add off-line unit tests

### ISSUE THREAD

**Issue by Qwebeck** [aI-lab-glider/ai-course-state-space-search#22]
At this moment it is hard for student to test function output for custom input, which can be useful when trying to pass BOBOT tests.
The problem can be worked around by creating "playground": files, where all required classes are created, so student can just call methods he want to call and pass to them custom input.

**Comment by mslazynski** [comment]
Maybe playground could be just a notebook with a correct setup?

**Comment by Qwebeck** [comment]
> Maybe playground could be just a notebook with a correct setup?

To my mind notebook, could be problematic, because it requires installation of an additional application, and don't give too much benefits. 

I think, that a file in specific folder (e.g `playgrounds`) with preconfigured would be enough.

**Comment by Qwebeck** [comment]
We've decided to create local unit tests, instead of playground, because they are more useful from educational point of view.
