### ISSUE TITLE
Diagrams

### ISSUE THREAD

**Issue by Qwebeck** [aI-lab-glider/ai-course-state-space-search#23]
At this moment it is hard for student to navigate in the code. 
I think, that it could be helpful to create a schematic diagram containing classes useful for student and demonstrating how they are connected between themselves and which methods do they have.

**Comment by Agwen12** [comment]
![searchProcess_NBAstar](https://user-images.githubusercontent.com/45673406/156616520-8e82debf-5cd1-495b-80a2-a956337d608b.jpg)

![generics_best_first](https://user-images.githubusercontent.com/45673406/156616806-ba5ce2fb-fa8b-40e7-be28-3b0766e9190a.jpg)

![grid_pathfinding](https://user-images.githubusercontent.com/45673406/156618553-816a6235-3e79-4e7d-aa9f-95e7d5ca0e2c.jpg)

![n_puzzle](https://user-images.githubusercontent.com/45673406/156616817-6cf94ce8-9a56-4521-8e2f-b9bf578e2382.jpg)

![UniformedSearch](https://user-images.githubusercontent.com/45673406/156618864-25ba5e32-cd7c-40b7-b15c-9aabb5166c1e.jpg)
